name: Ubuntu 20.04

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches: 
      - master
      - mhn-py3
  pull_request:
    branches:
      - master
      - mhn-py3

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-mhn-dependencies-master:
    runs-on: ubuntu-20.04

    if: ${{ github.ref == "refs/heads/master" }}

    steps:
      - uses: actions/checkout@v2

      - name: Clone latest MHN
        run: |
          cd /opt/
          sudo git clone https://github.com/wrharding/mhn.git
      
      - name: Install MHN dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python-pip
          sudo pip install --upgrade pip
          sudo apt install apt-transport-https -y
          sudo apt install build-essential -y
          sudo apt remove mongo* -y
        # Default mongodb install needs to be removed:
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#databases

      - name: Install hpfeeds
        run: |
          cd /opt/mhn/scripts/
          sudo ./install_hpfeeds.sh
      
      - name: Install mnemosyne
        run: |
          cd /opt/mhn/scripts/
          sudo ./install_mnemosyne.sh
      
      - name: Install honeymap
        run: |
          cd /opt/mhn/scripts/
          sudo ./install_honeymap.sh
  install-mhn-dependencies-mhn-py3:
    runs-on: ubuntu-20.04

    if: ${{ github.ref == 'refs/heads/mhn-py3' }}

    steps:
      - uses: actions/checkout@v2

      - name: Clone latest MHN
        run: |
          cd /opt/
          sudo git clone https://github.com/wrharding/mhn.git
          sudo git checkout mhn-py3
      
      - name: Install MHN dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python-pip
          sudo pip install --upgrade pip
          sudo apt install apt-transport-https -y
          sudo apt install build-essential -y
          sudo apt remove mongo* -y
        # Default mongodb install needs to be removed:
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#databases

      - name: Install hpfeeds
        run: |
          cd /opt/mhn/scripts/
          sudo ./install_hpfeeds.sh
      
      - name: Install mnemosyne
        run: |
          cd /opt/mhn/scripts/
          sudo ./install_mnemosyne.sh
      
      - name: Install honeymap
        run: |
          cd /opt/mhn/scripts/
          sudo ./install_honeymap.sh
